[workspace]
members = ["pgconf", "vector-service-proto", "vector-service-server"]
resolver = "2"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
