[graph]
features = ["pg16", "rand", "telemetry"]
targets = ["x86_64-unknown-linux-gnu"]

[advisories]
ignore = [
  { id = "RUSTSEC-2021-0127", reason = "pgrx strictly depends on serde_cbor" },
]

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  # "MPL-2.0",
  "Unicode-DFS-2016",
]
confidence-threshold = 0.93
private = { ignore = false }

[bans]
external-default-features = "allow"
highlight = "all"
multiple-versions = "deny"
wildcards = "deny"
workspace-default-features = "allow"

deny = [
  { crate = "ring", reason = "ring is not approved by the organization" },
  { crate = "rustls", reason = "rustls is not approved by the organization" },
]

skip = [
  { crate = "sync_wrapper@0.1", reason = "tower uses an old version" },
  { crate = "tower@0.4", reason = "tonic uses an old version" },
]

skip-tree = [
  { crate = "indexmap@1", reason = "tonic uses an old version" },
  { crate = "rustc_version@0.3", reason = "pgrx uses an old version" },
]
