services:
  development:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    env_file:
      - .env
    tty: true
    user: vscode
    volumes:
      - .:/workspace

  jaeger:
    image: jaegertracing/all-in-one:1.61.0
    ports:
      - "16686:16686"
    volumes:
      - jaeger:/tmp

  grafana:
    image: grafana/grafana-enterprise:11.2.1
    ports:
      - "13000:3000"
    volumes:
      - grafana:/var/lib/grafana

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.110.0
    command:
      - --config
      - /etc/otelcol-contrib/config.yaml
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml

  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "19090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

volumes:
  grafana:
  jaeger:
  prometheus:
